---
- name: CAP Network Deployment Playbook
  hosts: localhost
  gather_facts: No

  vars_files:
    - net_datastructure-new3.yml

  tasks:
    - name: Deploy Host and Router Namespaces
      ansible.builtin.import_tasks: 
        file: net_playbook-namespace.yml

    - name: Deploy Bridge Interfaces (Virtual Switch)
      ansible.builtin.import_tasks: 
        file: net_playbook-bridgecreate.yml

    - name: Deploy Host Veths (Virtual Connections)
      ansible.builtin.import_tasks: 
        file: net_playbook-vtest-host.yml
    
    - name: Deploy Router Veths (Virtual Connections)
      ansible.builtin.import_tasks: 
        file: net_playbook-vtest-routers.yml

    - name: Assign LAN Host IP Addresses & Enable Veths 
      ansible.builtin.import_tasks: 
        file: net_playbook-interface-lan.yml
    
    - name: Assign LAN Router IP Addresses & Enable Veths 
      ansible.builtin.import_tasks: 
        file: net_playbook-interface-wan-local.yml

    - name: Deploy Core Router and LAN Router Veths
      ansible.builtin.import_tasks: 
        file: net_playbook-vtest-routers-core.yml

    - name: Assign LAN Router and Core Router IP Addresses 
      ansible.builtin.import_tasks: 
        file: net_playbook-interface-wan-core.yml
    
    - name: Deploy NAT Router Interfaces and IP Addresses 
      ansible.builtin.import_tasks: 
        file: net_playbook-interface-nat.yml

    - name: Enable IP Forwarding
      ansible.builtin.import_tasks:
        file: net_playbook-ip-forwarding.yml

    - name: Deploy IP Routes
      ansible.builtin.import_tasks:
        file: net_playbook-ip-routes.yml
    
    - name: Enable iptables (Linux Firewall)
      ansible.builtin.import_tasks:
        file: net_playbook-iptables.yml

    - name: Launch Virtual Machines (VMs) via Python Script
      ansible.builtin.import_tasks:
        file: net_playbook-vm-launch.yml

    - name: Install and Launch iPerf on VMs
      ansible.builtin.import_tasks:
        file: net_playbook-vm-iperf.yml

    - name: Ping Test of Entire Network
      ansible.builtin.import_tasks:
        file: net_playbook-ping.yml

    - name: iPerf Test Results to VMs
      ansible.builtin.import_tasks:
        file: net_playbook-iperf.yml

