---
- name: CAP Network Deployment Playbook
  hosts: localhost
  gather_facts: No

  vars_files:
    - net_datastructure-new3.yml
    #- net_datastructure.yml

  tasks:
    - name: Deploy host and router namespace via imported task
      ansible.builtin.import_tasks: 
        file: net_playbook-namespace.yml

    - name: Deploy Bridge interfaces via imported task
      ansible.builtin.import_tasks: 
        file: net_playbook-bridgecreate.yml

    - name: Deploy host veths via imported task
      ansible.builtin.import_tasks: 
        file: net_playbook-vtest-host.yml
    
    - name: Deploy router veths via imported task
      ansible.builtin.import_tasks: 
        file: net_playbook-vtest-routers.yml

    - name: Assign host IPs & enable veths via imported task 
      ansible.builtin.import_tasks: 
        file: net_playbook-interface-lan.yml
    
    - name: Assign host IPs & enable veths via imported task 
      ansible.builtin.import_tasks: 
        file: net_playbook-interface-wan-local.yml

    - name: Create core router and lan router veths via imported task
      ansible.builtin.import_tasks: 
        file: net_playbook-vtest-routers-core.yml

    - name: Assign local router and core router addresses via imported task 
      ansible.builtin.import_tasks: 
        file: net_playbook-interface-wan-core.yml
    
    - name: Create nat router interfaces and assign addresses via imported task 
      ansible.builtin.import_tasks: 
        file: net_playbook-interface-nat.yml

    - name: Enable IP forwarding via imported task
      ansible.builtin.import_tasks:
        file: net_playbook-ip-forwardring.yaml
    
    