---
- name: iPerf
  hosts: localhost
  gather_facts: No

  vars: 
    iperf_ntarget: vm-north
    iperf_wtarget: vm-west

  tasks:

    - name: VM North 
      ansible.builtin.command: iperf --client vm-north
      register: iperf_nresults

    - name: VM West
      ansible.builtin.command: iperf --client vm-west
      register: iperf_wresults

    - name: Transfer Results in Megabits per Second 
      ansible.builtin.debug:
        msg: 
          - "North VM Results: {{ iperf_nresults.stdout_lines[6] }}"
          - "West VM Results: {{ iperf_wresults.stdout_lines[6] }}"

