---
- name: Router interface assignment
  hosts: localhost
  gather_facts: No

  vars_files:
    #- net_datastructure.yml
    - net_datastructure-new3.yml

  tasks:

    - name: "Test veth variable"
      ansible.builtin.debug:
        msg: "ip netns exec {{ item.get('hosts') }} ip address add {{ item.get('ip') }}{{ item.get('cidr') }} dev {{ item.get('hosts') }}_a"
      loop: "{{ Network['veth'][0]['interfaces'] | from_yaml }}"

    - name: "Test veth up"
      ansible.builtin.debug:
        msg: "ip netns exec {{ item.get('hosts') }} ip link set dev {{ item.get('hosts') }}_a up"
      loop: "{{ Network['veth'][0]['interfaces'] | from_yaml }}"

    - name: "Test lo up"
      ansible.builtin.debug:
        msg: "ip netns exec {{ item.get('hosts') }} ip link set dev lo up"
      loop: "{{ Network['veth'][0]['interfaces'] | from_yaml }}"

    # - name: "Assign local router interface ip on router_a link"
    #   ansible.builtin.command: "ip netns exec {{ item.get('hosts') }} ip address add {{ item.get('ip') }}{{ item.get('cidr') }} dev {{ item.get('hosts') }}_a"
    #   loop: "{{ Network['veth'][1]['interfaces'] | from_yaml }}"
    #   become: yes

    # - name: "Turn up local router_a link"
    #   ansible.builtin.command:  "ip netns exec {{ item.get('hosts') }} ip link set dev {{ item.get('hosts') }}_a up"
    #   loop: "{{ Network['veth'][1]['interfaces'] | from_yaml }}"
    #   become: yes

    # - name: "turn up local router lo link"
    #   ansible.builtin.command: "ip netns exec {{ item.get('hosts') }} ip link set dev lo up"
    #   loop: "{{ Network['veth'][1]['interfaces'] | from_yaml }}"
    #   become: yes
