---
- name: iPerf
  hosts: localhost
  gather_facts: No

  vars: 
    iperf_ntarget: vm-north
    iperf_wtarget: vm-west

  tasks:

    - name: iperf North
      ansible.builtin.command: iperf --client {{ iperf_ntarget }} --reportstyle C
      register: iperf_nresults

    - name: iperf West
      ansible.builtin.command: iperf --client {{ iperf_wtarget }} --reportstyle C
      register: iperf_wresults

    - name: output
      ansible.builtin.debug:
        msg: 
          - "North VM Results: {{ iperf_nresults.stdout }}"
          - "West VM Results: {{ iperf_wresults.stdout }}"

