---
- name: iPerf
  hosts: localhost
  gather_facts: No

  vars: 
    iperf_ntarget: vm-north
    iperf_wtarget: vm-south

  tasks:

    - name: iperf Worth
      ansible.builtin.command: iperf --client {{ iperf_ntarget }} --reportstyle C
      register: iperf_nresults

    - name: iperf West
      ansible.builtin.command: iperf --client {{ iperf_wtarget2 }} --reportstyle C
      register: iperf_wresults

    - name: output
      ansible.builtin.debug:
        msg: 
          - "North VM Results: {{ iperf_results.stdout }}"
          - "West VM Results: {{ iperf_results.stdout }}"

