---
- name: namespace creator
  hosts: localhost
  gather_facts: No

  vars_files:
    - net_datastructure.yml

  - name: Gather IP addresses
    ansible.builtin.iptables
      msg: "{{ item.get('subnet_ip') }}"
    loop: "{{ Network.subnets | from_yaml }}"

# tasks:
#    - name: Test print namespace
#      ansible.builtin.debug:
#        msg: "{{ item.get('name') }}"
#      loop: "{{ Network.subnets | from_yaml }}"

#    - name: Create network namespaces
#      community.general.ip_netns:
#        name: "{{ item.get('name') }}"
#      loop: "{{ Network.subnets | from_yaml }}"
#      become: yes

#    - name: Create bridges
#      ansible.builtin.command: ip link add name "{{ item.get('hosts') }}" type bridge
#      when: "{{ item.get('bridge') }}" 
#      loop: "{{ Network.subnets | from_yaml }}"
#      become: yes

#     ansible.builtin.command: ip link set dev "{{ item.get('hosts') }}" up
#      when: "{{ item.get('bridge') }}" 
#      loop: "{{ Network.subnets | from_yaml }}"
#      become: yes
#
#    - name: Capture brctl output
#      ansible.builtin.command: brctl show
#      register: command_output
#
#    - name: Show brctl output
#      ansible.builtin.debug:
#        var: command_output.stdout