---
- name: namespace creator
  hosts: localhost
  gather_facts: No

  vars_files:
    - net_datastructure.yml

  tasks:
    - name: Test print namespace
      ansible.builtin.debug:
        msg: "{{ item.name }}"
      loop: "{{ Network.subnets | from_yaml }}"