---
- name: namespace creator
  hosts: localhost
  gather_facts: No

  vars_files:
    - net_datastructure.yml

  tasks:
    # - name: Test print namespace
    #   ansible.builtin.debug:
    #     msg: "{{ item.get('name') }}"
    #   loop: "{{ Network.subnets | from_yaml }}"

    # - name: Create network namespaces
    #   community.general.ip_netns:
    #     name: "{{ item.get('name') }}"
    #   loop: "{{ Network.subnets | from_yaml }}"
    #   become: yes

    - name: Create network namespaces hosts
      community.general.ip_netns:
       name: "{{ item.get('hosts') }}"
      when: item.get('hosts') is defined
      loop: "{{ Network.subnets | from_yaml }}"
      become: yes

    - name: Create network namespaces routers 
      community.general.ip_netns:
       name: "{{ item.get('router') }}"
      when: item.get('router') is defined
      loop: "{{ Network.subnets | from_yaml }}"
      become: yes

    - name: Create bridges
      ansible.builtin.command: ip link add name "{{ item.get('name') }}"-bridge type bridge
      when: "{{ item.get('bridge') }}" 
      loop: "{{ Network.subnets | from_yaml }}"
      become: yes

    - name: Enable bridges to UP state
      ansible.builtin.command: ip link set dev "{{ item.get('name') }}"-bridge up
      when: "{{ item.get('bridge') }}" 
      loop: "{{ Network.subnets | from_yaml }}"
      become: yes

    - name: Capture brctl output
      ansible.builtin.command: brctl show
      register: command_output

    - name: Show brctl output
      ansible.builtin.debug:
        var: command_output.stdout

    - name: Deploy host veths via imported task
      ansible.builtin.import_tasks: 
        file: net_playbook-vtest-host.yml
    
    - name: Deploy router veths via imported task
      ansible.builtin.import_tasks: 
        file: net_playbook-vtest-routers.yml
    
    